language: objective-c
osx_image: xcode7.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - xctool \
    -workspace SwiftDailyAPI.xcworkspace \
    -scheme "SwiftDailyAPI-iOS" \
    -destination "OS=9.2,name=iPhone 6s Plus" \
    -sdk iphonesimulator \
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES \
    GCC_GENERATE_TEST_COVERAGE_FILES=YES \
    test
after_success:
  - bash <(curl -s https://codecov.io/bash)
