language: objective-c
osx_image: xcode7.2
before_install:
  - brew update
  - brew install carthage
  - pip install codecov
install:
  - carthage bootstrap --platform iOS
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild -workspace SwiftDailyAPI.xcworkspace -scheme "SwiftDailyAPI-iOS" -destination "OS=9.2,name=iPhone 6s Plus" test | xcpretty -c
after_success:
  - codecov
